### PR TITLE
Fix sunpy 3.1 compatibiltiy

### LINKED ISSUE #38: Fix compatibility with sunpy>=3.1
Is there a reason to pin `sunpy<3.1`? Is there something in the latest release that breaks something in eispac?

### PR DESCRIPTION
**Pull request by wtbarnes**
Fixes #38 

This fixes a test incompatibility with sunpy>=3.1

### CODE REVIEW

**Comment by MJWeberg** [comment]
Is there anything in sunpy or sunpy map that requires ndcube 2.0? I am getting some integer overflow errors when I try to use the .plot() method on a full, 3D cube of EIS data (both EISCubes and base NDCubes), so I am a bit wary of forcing users to upgrade immediately. Plotting 2D slices seems to work just fine though, which is what most users would be doing anyways, so perhaps it is a non-issue.

**Comment by wtbarnes** [comment]
> Is there anything in sunpy or sunpy map that requires ndcube 2.0? 

No. `sunpy` does not depend on ndcube. Similarly, ndcube(>=2.0) does not depend on sunpy.

> I am getting some integer overflow errors when I try to use the .plot() method on a full, 3D cube of EIS data (both EISCubes and base NDCubes), so I am a bit wary of forcing users to upgrade immediately. Plotting 2D slices seems to work just fine though, which is what most users would be doing anyways, so perhaps it is a non-issue.

Huh that is strange. If this is happening on bare ndcubes, maybe it should be reported upstream to the ndcube repo? Is this in animations in a notebook or in a normal matplotlib Qt interface?

My main reason for pinning to >=2.0 is that I'm not sure that maintaining compatibility between pre and post 2.0 is a good idea. It may be possible at the moment, but the burden of maintaining compatibility with both versions is only likely to increase. I think for a pre-1.0 package like eispac, it is perfectly reasonable to force users to update.

**Comment by Cadair** [comment]
> My main reason for pinning to >=2.0 is that I'm not sure that maintaining compatibility between pre and post 2.0 is a good idea.

I would agree with this, the ndcube 2.0 code base is very different from 1.0, even if your library code isn't using the API your users presumably will and will get very confused if you can swap between them with the same version of eispac.

> I am getting some integer overflow errors when I try to use the .plot() method on a full, 3D cube of EIS data (both EISCubes and base NDCubes)

If you can reliably reproduce this please open an issue upstream so we can debug it!

**Comment by MJWeberg** [comment]
Fair points. I will go ahead and merge this is and increase the required version numbers. 

Finally getting back to testing the plotting of full cubes of EIS data and will open a report on the NDCube when I know more.

**Pull request merged**
